# Generated by Django 5.0.3 on 2024-03-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Nome da descrição', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor da despesa', max_digits=10)),
                ('date_expenser', models.DateField(help_text='data da descrição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.category')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
